basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    basic.pause(1)
    basic.showIcon(IconNames.Sad)
    basic.pause(1)
    basic.showIcon(IconNames.Angry)
    basic.pause(1)
    basic.showIcon(IconNames.Asleep)
    basic.pause(1)
    basic.showIcon(IconNames.Meh)
    basic.pause(1)
    basic.showIcon(IconNames.Surprised)
    basic.pause(1)
    basic.showIcon(IconNames.Silly)
    basic.pause(1)
})
